### ISSUE TITLE
Diff fissues with plugin usage

### ISSUE THREAD

**Issue by iv-enovation** [quickom-foundation/moodle-mod_quickom#1]
1) Warning: Cannot modify header information - headers already sent in /var/www/html/ticket/moodle_39_dev/mod/quickom/extend.php on line 32

It's a big problem as it breaks all Ajax throughout a whole Moodle - when an Ajax mechanism fires up it always receives headers from extend.php and always displays an empty error

2) When creating an activity (with password):

> Notice: Trying to get property 'id' of non-object in /var/www/html/ticket/moodle_39_dev/mod/quickom/locallib.php on line 153
> Notice: Undefined index: alternative_hosts in /var/www/html/ticket/moodle_39_dev/mod/quickom/mod_form.php on line 164
> Notice: Undefined property: stdClass::$option_host_video in /var/www/html/ticket/moodle_39_dev/mod/quickom/classes/webservice.php on line 323
> Notice: Undefined property: stdClass::$option_audio in /var/www/html/ticket/moodle_39_dev/mod/quickom/classes/webservice.php on line 324
> Notice: Undefined property: stdClass::$webinar in /var/www/html/ticket/moodle_39_dev/mod/quickom/classes/webservice.php on line 342
> Notice: Undefined property: stdClass::$recurring in /var/www/html/ticket/moodle_39_dev/mod/quickom/classes/webservice.php on line 345
> Notice: Undefined property: stdClass::$option_jbh in /var/www/html/ticket/moodle_39_dev/mod/quickom/classes/webservice.php on line 346
> Notice: Undefined property: stdClass::$option_participants_video in /var/www/html/ticket/moodle_39_dev/mod/quickom/classes/webservice.php on line 347
> Notice: Undefined property: stdClass::$alias in /var/www/html/ticket/moodle_39_dev/mod/quickom/extend.php on line 362

3) 
- in public function get_meeting_webinar_info($id, $webinar)  in quickom/classes/webservice.php there is code after return
- immediate return in test_format_participant_matching() in tests/get_meeting_reports_test.php

4) Cron fails at "Update classroom settings from Quickom"
Error:
> !!! Exception - Argument 2 passed to populate_quickom_from_response() must be an instance of stdClass, array given, called in [dirroot]/mod/quickom/classes/task/update_meetings.php on line 89 !!!

**Comment by ntquangkk** [comment]
Hi Iv-Enovation, 

Thank you for reporting the issues,

We have fixed the bugs. 

Best regards,
Quickom.
