### ISSUE TITLE
Missing instruction

### ISSUE THREAD

**Issue by behoof** [quickom-foundation/moodle-mod_quickom#2]
Missing instruction about field Quickom home page URL

**Comment by ntquangkk** [comment]
Hi Behoof, 

Thank you for reporting the issue.

The "Quickom home page URL" field is where you either put a url to your custom page or just leave it blank.

Instructions are posted in the github wiki [here](https://github.com/quickom-foundation/moodle-mod_quickom/wiki/Quickom-Classroom-plugin-configurations). 
Or you can find the information in the README.md file.

Best regards,
Quickom.
